version: '3.3'
services:
    csvserver:
        image: infracloudio/csvserver:latest
        privileged: true
        volumes:
            - '/root/csvserver/solution/inputFile:/csvserver/inputdata'
        ports:
            - '9393:9300'
        environment:
            - CSVSERVER_BORDER=Orange
        extra_hosts:
            - "host.docker.internal:host-gateway"
    
    prometheus:
        image: prom/prometheus:v2.22.0
        container_name: prometheus
        ports:
            - 9090:9090
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - csvserver   
        extra_hosts:
            - "host.docker.internal:host-gateway"
